version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - php

  php:
    image: php:8-fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./html:/var/www/html
